UVCRMS/Models/SaveStudentResult.cs
using System.ComponentModel.DataAnnotations;

namespace UVCRMS.Models
{
    public class SaveStudentResult
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Select Course"), Display(Name = "Student Reg. No.")]
        public int StudentId { get; set;}

        [Required(ErrorMessage = "Please Select Course"), Display(Name = "Select Course")]
        public int CourseId { get; set; }

        [Required(ErrorMessage = "Please Select Grade"), Display(Name = "Select Grade")]
        public int GradeId { get; set; }

        [StringLength(50)]
        public string? Status { get; set; }

        [DataType(DataType.Date), Display(Name = "Please Select  Date")]
        public string? Date { get; set; }


        public Student? Student { get; set; }
        public Course? Course { get; set; }
        public Grade? Grade { get; set;}


    }
}

UVCRMS/Controllers/SaveStudentResultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UVCRMS.Data;
using UVCRMS.Models;

namespace UVCRMS.Controllers
{
    public class SaveStudentResultController : Controller
    {
        private readonly ApplicationDbContext db;

        // Updated Version
        public SaveStudentResultController(ApplicationDbContext dbContext) => db = dbContext;
        //public SaveStudentResultController(ApplicationDbContext dbContext)
        //{
        //    db = dbContext;
        //}

        public IActionResult Index()
        {
            return View(db.SaveStudentResults.ToList());
        }

        public IActionResult ViewResult()
        {
            ViewBag.Students = new SelectList(db.Students.ToList(), "Id", "StudentRegNo");
            ViewBag.Courses = new SelectList(db.Courses.ToList(), "Id", "CoursName");
            ViewBag.Departments = new SelectList(db.Departments.ToList(), "Id", "DepartmentCode");
            ViewBag.Grades = new SelectList(db.Grades.ToList(), "Id", "GradeLetter");

            return View();
        }

        public IActionResult CreateEnrollCourse()
        {
            ViewBag.Students = new SelectList(db.Students.ToList(), "Id", "StudentRegNo");
            ViewBag.Courses = new SelectList(db.Courses.ToList(), "Id", "CoursName");
            ViewBag.Departments = new SelectList(db.Departments.ToList(), "Id", "DepartmentCode");
            ViewBag.Grades = new SelectList(db.Grades.ToList(), "Id", "GradeLetter");

            return View();
        }

        [HttpPost]
        public IActionResult CreateEnrollCourse(SaveStudentResult saveStudentResult)
        {
            saveStudentResult.Status = "Enroll";

            db.SaveStudentResults.Add(saveStudentResult);
            db.SaveChanges();

            TempData["student_result_successfully"] = "Student Result Successfully";
            return RedirectToAction("CreateEnrollCourse", "EnrollCourse");
        }

        //public IActionResult PrintAll()
        //{
        //    var q = new ActionAsPdf("ViewResult");
        //    return q;
        //}

        public JsonResult GetStudentNameEmailDeptByRegNo(int studentId)
        {
            var students = db.SaveStudentResults.Where(x => x.StudentId == studentId).ToList();

            return Json(students);
        }

        public JsonResult GetStudentNameEmailDeptByStId(int studentId)
        {
            var student = db.Students.FirstOrDefault(x => x.Id == studentId);

            return Json(student);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UVCRMS/Views/SaveStudentResult/CreateEnrollCourse.cshtml
@model UVCRMS.Models.SaveStudentResult
@* @using FlashMessage *@
@{
    ViewBag.Title = "CreateEnrollCourse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @* <h3 style="color:green;text-align:center">@Html.Flash()</h3> *@

    <h4>Save Student Result</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "Reg No", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.StudentId, ViewBag.Students as SelectList, "--Select--", new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" readonly="readonly" name="StudentName" id="StudentName" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" readonly="readonly" name="StudentEmail" id="StudentEmail" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StudentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            <input type="text" readonly="readonly" name="DepartmentId" id="DepartmentId" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CourseId, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CourseId, ViewBag.Courses as SelectList, "--Select--", new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.GradeId, "Grade ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.GradeId, ViewBag.Grades as SelectList, "--Select--", new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.GradeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>

@section scripts
{
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>


    $(document).ready(function () {
        $("#StudentId").change(function () {
            var studentId = $("#StudentId").val();


            $("#StudentName").val('');
            $("#StudentEmail").val('');
            $("#DepartmentId").val('');

            var parameter = { studentId: studentId }

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudentNameEmailDeptByRegNo", "EnrollCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(parameter),
                success: function (data) {
                    $("#StudentName").val(data.StudentName);
                    $("#StudentEmail").val(data.StudentEmail);
                    $("#DepartmentId").val(data.Department.DepartmentCode);
                }
            });


        });

        $("#Date").datepicker();

        });
    </script>
}

UVCRMS/Views/SaveStudentResult/Index.cshtml
@model IEnumerable<UVCRMS.Models.SaveStudentResult>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "CreateEnrollCourse")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade.GradeLetter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
          Action
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade.GradeLetter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.StudentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

UVCRMS/Views/SaveStudentResult/ViewResult.cshtml
@model UVCRMS.Models.SaveStudentResult

@{
    ViewBag.Title = "View Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EnrollInACourse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Reg No", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StudentId, ViewBag.Students as SelectList, "--Select--", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" readonly="readonly" name="StudentName" id="StudentName" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" readonly="readonly" name="StudentEmail" id="StudentEmail" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "Department", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <input type="text" readonly="readonly" name="DepartmentId" id="DepartmentId" class="form-control" />
            </div>
        </div>

        <table id="myTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th style="width: 15%">Course Code</th>
                    <th style="width: 40%">Name</th>
                    <th style="width: 15%">Grade</th>

                </tr>
            </thead>

        </table>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link href="~/Content/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css" />

@section scripts
{
    @*these down all link here https://datatables.net/extensions/buttons/examples/initialisation/export.html*@

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/scripts/datatables/jquery.datatables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

    <script>


    $(document).ready(function () {
        $("#StudentId").change(function () {
            var studentId = $("#StudentId").val();

            $("#studentInfo").empty();

            $("#StudentName").val('');
            $("#StudentEmail").val('');
            $("#DepartmentId").val('');



            var parameter = { studentId: studentId }

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudentNameEmailDeptByStId", "SaveStudentResult")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(parameter),
                success: function (data) {
                    $("#StudentName").val(data.StudentName);
                    $("#StudentEmail").val(data.StudentEmail);
                    $("#DepartmentId").val(data.Department.DepartmentCode);

                }
            });

              $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudentNameEmailDeptByRegNo", "SaveStudentResult")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(parameter),
                success: function (data) {
                    $("#myTable").show();
                    table.clear().draw(false);

                    $.each(data, function (key, value) {

                        table.row.add([
                            value.Course.CourseCode, value.Course.CoursName, value.Grade.GradeLetter
                        ]
                        ).draw(false);
                    });
                }
            });

        });

        var table = $('#myTable').DataTable({

            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });

        });

    </script>
}